### ISSUE TITLE
domain change needed (from .com to .net)

### ISSUE THREAD

**Issue by xavidp** [lemuscanovas/meteoclimaticR#3]
It seems that meteoclimatic changed the domain to allow fetching data through their feed.
See:
https://github.com/emf-creaf/meteospain/issues/24#issue-2586226315

This package is still using the old .com domain from meteoclimatic.

**Comment by lemuscanovas** [comment]
Gràcies, @xavidp ! De nou, disculpes per l'enorme retard en al resposta.
Salut,
Marc

**Comment by xavidp** [comment]
De res, Marc, un plaer contribuir amb un granet de sorra :-)
