### ISSUE TITLE
Error al intentar descargar datos

### ISSUE THREAD

**Issue by Aimonius** [lemuscanovas/meteoclimaticR#4]
Al intentar descargar datos me lanza este error:

`ppcc <- current_download(id = c("ESCAT","ESPVA","ESIBA"),save_excel = F)
StartTag: invalid element name
Extra content at the end of the document
Error: 1: StartTag: invalid element name
2: Extra content at the end of the document`

Utilizo la última versión de desarrollo disponible aquí.

Saludos y gracias.

**Comment by xavidp** [comment]
hola jesbrz. Ha cambiado la url para descargar datos de meteoclimatic. Prueba si quieres si con mi fork te funciona, hasta que lemuscasanovas pueda mirar de sincronizar los cambios:
https://github.com/xavidp/meteoclimaticR/tree/master

**Comment by Aimonius** [comment]
Funciona perfectamente. Gracias @xavidp

**Comment by lemuscanovas** [comment]
Hola a todos, 

Mil disculpas por el enorme retraso en la respuesta. No sé porque no tengo activas las notificaciones en este repositorio. 
@xavidp , gracias por los cambios sugeridos :). Ya están aprobados y todos funcionandos!

**Comment by xavidp** [comment]
De nada, un placer, y gracias a ti por crear y mantener este paquete :-)
